### ISSUE TITLE
CV2 Package 

### ISSUE THREAD

**Issue by kakachiex2** [chrisfreilich/virtuoso-nodes#11]
What is cv2 in the requirement don't install I get this error.
ERROR: Could not find a version that satisfies the requirement cv2 (from versions: none)
ERROR: No matching distribution found for cv2

**Comment by kakachiex2** [comment]
In Pypi web there are several packages with CV and I don't know which one is correct

**Comment by kakachiex2** [comment]
It would be good to match similar requirement as Layer style extension to minimize compatibility errors.
https://github.com/chflame163/ComfyUI_LayerStyle

**Comment by chrisfreilich** [comment]
I've updated the requirements.txt file to properly install the opencv-python package, where cv2 resides. This should fix it.

**Comment by kakachiex2** [comment]
Thanks a lot chrisfreilich great node extension.
