### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by imperator-maximus** [chrisfreilich/virtuoso-nodes#3]
Hello,

great work!
I am wondering which license do you have (e.g. GPL, MIT,...)?

Thank you!

**Comment by chrisfreilich** [comment]
I hadn't really thought about it honestly! But, I've decided on GNU GENERAL PUBLIC LICENSE.

**Comment by imperator-maximus** [comment]
Thank you! 
I just added custom element for gradient + forms + rules + workflows:
![image](https://github.com/chrisfreilich/virtuoso-nodes/assets/4406586/d4a87dc4-9ef8-4b0c-9f08-939d5a299074)

This is not Photoshop 😉

**Comment by chrisfreilich** [comment]
I'm not sure what I'm looking at, but it looks amazing! Is this a custom UI for Comfy? I'd love to chat with you!

**Comment by imperator-maximus** [comment]
This is a huge application. No official announcement yet. Perfect integration of ComfyUI. 
Are you on Discord?

**Comment by chrisfreilich** [comment]
That is very exciting! Yep, I'm on Discord, at cfreilich.
