### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Metal-dude** [chrisfreilich/virtuoso-nodes#5]
Hi, 

The installation fails and I've the following message  :

>    File "W:\ComfyUI_windows_portable\ComfyUI\custom_nodes\virtuoso-nodes\blendmodes.py", line 10, in <module>
>     from blend_modes import grain_extract, grain_merge
> ModuleNotFoundError: No module named 'blend_modes'
> 
> Cannot import W:\ComfyUI_windows_portable\ComfyUI\custom_nodes\virtuoso-nodes module for custom nodes: No module named 'blend_modes'

All the requirements are installed, including blend_modes : 

> Requirement already satisfied: blend_modes in c:\users\pc2\appdata\local\programs\python\python310\lib\site-packages (2.1.0)
> Requirement already satisfied: numpy in c:\users\pc2\appdata\local\programs\python\python310\lib\site-packages (from blend_modes) (1.26.4)

**Comment by chrisfreilich** [comment]
It looks like you're using the portable install of ComfyUI, but the blend_modes package is installed in your main Python environment.  

Try using the pip installer in W:\ComfyUI_windows_portable\python_embeded\Scripts by calling it with the full path name:

 W:\ComfyUI_windows_portable\python_embeded\Scripts\pip install blend_modes

**Comment by Metal-dude** [comment]
Thanks for spotting the problem.

I was able to run Virtuoso Nodes by typing the following commands in a command prompt :

- first single command, on a single line (it is necessary to write the precise location of python.exe , then to insert a space, then to write the precise location of pip.exe) :

> W:\ComfyUI_windows_portable\python_embeded\python.exe W:\ComfyUI_windows_portable\python_embeded\Scripts\pip.exe install blend_modes

- second single command, on a single line (it is also necessary to write the precise location of python.exe , then to insert a space, then to write the precise location of pip.exe) :

> W:\ComfyUI_windows_portable\python_embeded\python.exe W:\ComfyUI_windows_portable\python_embeded\Scripts\pip.exe install blurgenerator


Once these commands are done, it is possible to check that blend_modes and blurgenerator are installed in python embeded :

> W:\ComfyUI_windows_portable\python_embeded\python.exe W:\ComfyUI_windows_portable\python_embeded\Scripts\pip.exe list

Then Virtuoso Nodes is running on the next launch or Comfyui.
