### ISSUE TITLE
Issue when using outputs for anything other than saving results

### ISSUE THREAD

**Issue by masaint** [chrisfreilich/virtuoso-nodes#6]
![image](https://github.com/chrisfreilich/virtuoso-nodes/assets/135912013/59b7c287-91bd-4832-a4e3-69f0fed85262)

Hey, love the nodes, been looking for some like this for ages now but having some trouble too.

I want to pre-process some images prior to doing some img2img upscales, however I'm just getting blank outputs. It's not my workflow or other nodes, it's absolutely fine if I circumvent these nodes, however the second I do include these nodes as an input to any node other than preview/save image, there are issues. 

Would be greatly appreciated if you could look into this 🙏

**Comment by chrisfreilich** [comment]
Hi Mark,

I'm afraid there's not enough information here to try to help you. The file that your error is occurring in is a core ComfyUI file, so it's really hard to say what's going on.

I'm able to use multiple Virtuoso Nodes before an I2I image creation without problem:

![image](https://github.com/chrisfreilich/virtuoso-nodes/assets/108036952/c6fa201d-2505-488b-b37d-c1f5a320d7e0)

Maybe post your workflow?
