### ISSUE TITLE
Errors in the install requirements.txt!

### ISSUE THREAD

**Issue by merecesarchviz** [chrisfreilich/virtuoso-nodes#9]
Hi I install the nodes in comfyui but during the installation it seems that the node get errors that im show below and dont install correctly! any tip what is happening and how to solve it?

![imagem](https://github.com/chrisfreilich/virtuoso-nodes/assets/79140456/e1ae7373-8a31-4138-b329-a90a5c6578fa)

**Comment by chrisfreilich** [comment]
Can you modify the requirements.txt file? Replace ```cv2``` with ```opencv-python``` and then rerun the ```pip install -r requirements.txt``` command in the virtuoso-nodes directory. Let me know if that works!
